// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/ratelimiter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RateLimiter_CheckQuota_FullMethodName = "/ratelimiter.RateLimiter/CheckQuota"
	RateLimiter_Gossip_FullMethodName     = "/ratelimiter.RateLimiter/Gossip"
)

// RateLimiterClient is the client API for RateLimiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimiterClient interface {
	CheckQuota(ctx context.Context, in *QuotaRequest, opts ...grpc.CallOption) (*QuotaResponse, error)
	Gossip(ctx context.Context, in *GossipMessage, opts ...grpc.CallOption) (*GossipResponse, error)
}

type rateLimiterClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimiterClient(cc grpc.ClientConnInterface) RateLimiterClient {
	return &rateLimiterClient{cc}
}

func (c *rateLimiterClient) CheckQuota(ctx context.Context, in *QuotaRequest, opts ...grpc.CallOption) (*QuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaResponse)
	err := c.cc.Invoke(ctx, RateLimiter_CheckQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) Gossip(ctx context.Context, in *GossipMessage, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, RateLimiter_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimiterServer is the server API for RateLimiter service.
// All implementations must embed UnimplementedRateLimiterServer
// for forward compatibility.
type RateLimiterServer interface {
	CheckQuota(context.Context, *QuotaRequest) (*QuotaResponse, error)
	Gossip(context.Context, *GossipMessage) (*GossipResponse, error)
	mustEmbedUnimplementedRateLimiterServer()
}

// UnimplementedRateLimiterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimiterServer struct{}

func (UnimplementedRateLimiterServer) CheckQuota(context.Context, *QuotaRequest) (*QuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckQuota not implemented")
}
func (UnimplementedRateLimiterServer) Gossip(context.Context, *GossipMessage) (*GossipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedRateLimiterServer) mustEmbedUnimplementedRateLimiterServer() {}
func (UnimplementedRateLimiterServer) testEmbeddedByValue()                     {}

// UnsafeRateLimiterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimiterServer will
// result in compilation errors.
type UnsafeRateLimiterServer interface {
	mustEmbedUnimplementedRateLimiterServer()
}

func RegisterRateLimiterServer(s grpc.ServiceRegistrar, srv RateLimiterServer) {
	// If the following call panics, it indicates UnimplementedRateLimiterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimiter_ServiceDesc, srv)
}

func _RateLimiter_CheckQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).CheckQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_CheckQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).CheckQuota(ctx, req.(*QuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).Gossip(ctx, req.(*GossipMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimiter_ServiceDesc is the grpc.ServiceDesc for RateLimiter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimiter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ratelimiter.RateLimiter",
	HandlerType: (*RateLimiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckQuota",
			Handler:    _RateLimiter_CheckQuota_Handler,
		},
		{
			MethodName: "Gossip",
			Handler:    _RateLimiter_Gossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ratelimiter.proto",
}
